name: Rust Reusable Workflow called from matrix

on:
  workflow_call:
    inputs:
      os:
        description: 'What OS should we run'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  reusable-build-steps:
    if: |
        contains(inputs.os,'linux') ||
        contains(inputs.os,'ubuntu') ||
        contains(inputs.os,'windows')

    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build --lib
        run: cargo build --lib --verbose
      - name: Run tests --lib
        run: cargo test --lib --verbose
      - name: Run clippy --lib
        run: cargo clippy --lib

  linux-only-build-steps:
    if: |
        contains(inputs.os,'linux') ||
        contains(inputs.os,'ubuntu')

    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build main.rs - sys-inf-rs
        run: cargo build --release --verbose
      - name: Build main.rs - sys-inf-rs with static glibc
        run: RUSTFLAGS="-C target-feature=+crt-static" cargo build --release --target x86_64-unknown-linux-gnu --verbose

      - name: Artifact target dir
        uses: actions/upload-artifact@v3
        with:
          name: sys-inf-rs-target-dir
          path: target/

      - name: Artifact static x86_64 target/x86_64-unknown-linux-gnu/release/sys-inf-rs
        uses: actions/upload-artifact@v3
        with:
          name: sys-info-rs-static
          path: target/x86_64-unknown-linux-gnu/release/sys-inf-rs

      - name: Artifact target/release/sys-inf-rs
        uses: actions/upload-artifact@v3
        with:
          name: sys-inf-rs
          path: target/release/sys-inf-rs
