name: Rust Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    uses: ./.github/workflows/rust-reusable.yml

    with:
      os: ${{ matrix.os }}
