name: Rust Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Build --lib
        run: cargo build --lib --verbose
      - name: Run tests --lib
        run: cargo test --lib --verbose
      - name: Run clippy --lib
        run: cargo clippy --lib
